### PR TITLE
[TEST] Change PHPUnit test to Pest laravel test.

### PR DESCRIPTION
**Pull request by cgarcia-lightit**
# ⚡ TaskTitle - [CU-86drbt7cc](https://app.clickup.com/t/86drbt7cc) ⚡

## 💻 What type of change is this?

- [ ] 💎 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Styling
- [x] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build / CI

## ⭐ Description

I Remove the old PHPUnit test to the Pest test and remove unnecessary warnings on the phpstan.neon

## 📷 Screenshots
Screenshot 2024-03-13 at 08 17 28

## ✅ Checklist

- [x] This PR can be merged (it is not a draft, work in progress, or blocked on another PR)
- [ ] I have tested this change locally in multiple screen sizes
- [x] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by sojeda — CHANGES_REQUESTED** [review]
There is an error in the pipeline

**Comment by cgarcia-lightit** [comment]
> There is an error in the pipeline

@sojeda In this case the error occurred because in our Laravel boilerplate, we don't have any tests in the folder Unit, and is mandatory to have a test in it. Evaluating the structure I guess we can remove that folder from the project and from the configuration in the phpunit.xml too, or we can make a test inside the Unit folder ( a fake test,  I did it ), to mitigate this error, I saw that works, but in my opinion, this is an ugly way to silent the error on the pipeline. But we have to discuss if we prefer to have neatness in our boilerplate and delegate the configuration of the Unit folder and phpunit.xml to each new project or just use the fake test but maintain the consistency of the Unit folder, let me know what we decide.

**Comment by cgarcia-lightit** [comment]
@sojeda any new?

**Comment by sojeda** [comment]
> > There is an error in the pipeline
> 
> @sojeda In this case the error occurred because in our Laravel boilerplate, we don't have any tests in the folder Unit, and is mandatory to have a test in it. Evaluating the structure I guess we can remove that folder from the project and from the configuration in the phpunit.xml too, or we can make a test inside the Unit folder ( a fake test, I did it ), to mitigate this error, I saw that works, but in my opinion, this is an ugly way to silent the error on the pipeline. But we have to discuss if we prefer to have neatness in our boilerplate and delegate the configuration of the Unit folder and phpunit.xml to each new project or just use the fake test but maintain the consistency of the Unit folder, let me know what we decide.

I prefer to have a unit test, like Laravel has, simply to demonstrate that they exist

**Pull request merged**
